<a href="https://colab.research.google.com/github/alexiswang10/Tibame_online0616/blob/main/tibame_20250705_04_%E8%80%81%E5%B8%AB%E5%BB%BA%E8%AD%B0%E5%AF%AB%E6%B3%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import urllib.request as req
import pandas as pd

url = "https://github.com/Elwing-Chou/tibame_online_0616/raw/refs/heads/main/tabelog.csv"
req.urlretrieve(url, "tabelog.csv")
df = pd.read_csv("tabelog.csv", encoding="utf-8", index_col=0)
df

,en,href,rating,area_genre,dinner_price,lunch_price,holiday
0,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,4.28,"參宮橋車站 / 法式料理, 蛋糕","JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999",-
1,AIGRE DOUCE,https://tabelog.com/tw/tokyo/A1305/A130502/130...,4.03,"目白車站 / 蛋糕, 馬卡龍","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期一, 星期二"
2,a tes souhaits!,https://tabelog.com/tw/tokyo/A1320/A132001/130...,4.01,"西荻窪車站 / 蛋糕, 甜點",- JPY 999,- JPY 999,"星期一, 星期二"
3,L'Atelier à Ma Façon,https://tabelog.com/tw/tokyo/A1317/A131715/132...,4.00,"上野毛車站 / 甜點, 咖啡店","JPY 4,000 - JPY 4,999","JPY 4,000 - JPY 4,999",-
4,Patisserie Ryoko,https://tabelog.com/tw/tokyo/A1316/A131603/131...,3.99,"高輪台車站 / 蛋糕, 泡芙, 西式甜點",-,- JPY 999,"星期一, 星期二, 星期三, 星期四"
...,...,...,...,...,...,...,...
95,Criollo Nakameguro Ten,https://tabelog.com/tw/tokyo/A1317/A131701/130...,3.77,"中目黑車站 / 蛋糕, 巧克力, 馬卡龍","JPY 4,000 - JPY 4,999",-,-
96,Le Grenier à Pan Koji Chiyocho Ten,https://tabelog.com/tw/tokyo/A1308/A130803/130...,3.77,"半藏門車站 / 麵包, 三明治, 蛋糕",- JPY 999,- JPY 999,-
97,LA BOUTIQUE de Joel Robushon Ebisu Garden Plac...,https://tabelog.com/tw/tokyo/A1303/A130302/130...,3.77,"惠比壽車站 / 麵包, 蛋糕, 三明治","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-
98,Chimoto,https://tabelog.com/tw/tokyo/A1317/A131702/130...,3.77,"都立大學車站 / 日式點心, 日式甜點店, 剉冰","JPY 1,000 - JPY 1,999",- JPY 999,"星期三, 星期四"
99,Fiorentina Pastry Boutique,https://tabelog.com/tw/tokyo/A1307/A130701/130...,3.77,"六本木車站 / 蛋糕, 麵包, 巧克力","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-

In [4]:
# 可以掛接雲端硬碟來當你的永久儲存
# df.to_csv("drive/MyDrive/tabelog0705.csv", encoding="utf-8")



```
pandas兩大操作
1. 過濾(filter): 帶入跟你資料筆數依樣多的True/False
2. 轉換(apply):  


```

In [ ]:
df["rating"] * 2

In [ ]:
# apply(轉換流程): 轉換流程是一個錦囊(不加小括號)
rating_2 = df["rating"] * 2
rating_2.apply(round)

In [ ]:
def flow(n):
    return round(n * 2, 1)
df["rating"].apply(flow)



```
這裡一個值要變出兩行
pd.DataFrame: 二維, 有行有列的
pd.Series: 一維, 一行/一列
```

In [ ]:
def flow(n):
    return pd.Series({"a":n, "b":2*n})
df["rating"].apply(flow)

In [ ]:
def flow(data):
    data_split = data.split(" / ")
    if len(data_split) == 1:
        area = data_split[0]
        genre = "-"
    else:
        area = data_split[0]
        genre = data_split[1]
    return pd.Series({"area":area, "genre":genre})

df[["area", "genre"]] = df["area_genre"].apply(flow)
df

In [ ]:
holiday_keys = [
    "星期一",
    "星期二",
    "星期三",
    "星期四",
    "星期五",
    "星期六",
    "星期日",
]

def flow(data):
    holiday = {}
    for key in holiday_keys:
        holiday[key] = "Y"

    for key in holiday:
        if key in data:
            holiday[key] = "N"
    return pd.Series(holiday)

df[holiday_keys] = df["holiday"].apply(flow)
df

In [ ]:
df["holiday"].value_counts()

In [8]:
# 禮拜六或者禮拜日有開 賣馬卡龍的店







df["genre"].str.contains("馬卡龍")

0     False
1      True
2     False
3     False
4     False
      ...
95     True
96    False
97    False
98    False
99    False
Name: genre, Length: 100, dtype: bool



```
Everything is an object: 任何東西都是有型態的, 都有他配合的操作

字典[key]

print(3+2)

print: 函式型態
(3+2): 針對這型態的操作

!!! 函式是一種型態

函式: 常用的幾句程式碼包在一起變成一份SOP

print: 步驟型態(還沒做)
(3+2): 真的把步驟操作一遍得到結果

```

In [ ]:
def add(n1, n2):
    ans = n1 + n2
    return ans
b = add
b(3, 5)

import random
def realrandom(t):
    if t == 0:
        return random.randint
    else:
        return random.uniform

realrandom(1)(3, 5)

3.645866854815284